### ISSUE TITLE
Problem with icons (404 - Not found)

### ISSUE THREAD

**Issue by jgarciao** [flathub/com.endlessm.HatchPreviewer#1]
The icon for this app doesn't appear in https://beta.flathub.org/apps/details/com.endlessm.HatchPreviewer

The appstream data for this app has this information:

```
<icon type="remote">https://raw.githubusercontent.com/endlessm/hatch-previewer/master/icons/256x256/hatch-previewer.png</icon>
<icon type="remote">https://raw.githubusercontent.com/endlessm/hatch-previewer/master/icons/128x128/hatch-previewer.png</icon>
<icon type="remote">https://raw.githubusercontent.com/endlessm/hatch-previewer/master/icons/64x64/hatch-previewer.png</icon>
```

But accessing directly with Google Chrome says 404-Not found
https://raw.githubusercontent.com/endlessm/hatch-previewer/master/icons/128x128/hatch-previewer.png

**Comment by TingPing** [comment]
This was fixed upstream: https://github.com/endlessm/hatch-previewer/commit/c9cdc1d84d95e2e17a64aef76e2234d2d319016b

This just needs to be updated.

**Comment by ptomato** [comment]
I moved the manifest to the current master commit, so this should be fixed after it rebuilds.

**Comment by jgarciao** [comment]
Thank you!

El dia 21 març 2018 7:20 p. m., "P. F. Chimento" <notifications@github.com>
va escriure:

**Comment by jgarciao** [comment]
The icon is still missing in the appdata (and the website)

In the past with another app @nedrichards had to clean the build cache in order to make the icon appear
